// Generated by gencpp from file amazon/Object.msg
// DO NOT EDIT!


#ifndef AMAZON_MESSAGE_OBJECT_H
#define AMAZON_MESSAGE_OBJECT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace amazon
{
template <class ContainerAllocator>
struct Object_
{
  typedef Object_<ContainerAllocator> Type;

  Object_()
    : header()
    , bin_id(0)
    , object_id(0)  {
    }
  Object_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , bin_id(0)
    , object_id(0)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef int64_t _bin_id_type;
  _bin_id_type bin_id;

   typedef int64_t _object_id_type;
  _object_id_type object_id;




  typedef boost::shared_ptr< ::amazon::Object_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::amazon::Object_<ContainerAllocator> const> ConstPtr;

}; // struct Object_

typedef ::amazon::Object_<std::allocator<void> > Object;

typedef boost::shared_ptr< ::amazon::Object > ObjectPtr;
typedef boost::shared_ptr< ::amazon::Object const> ObjectConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::amazon::Object_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::amazon::Object_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace amazon

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'amazon': ['/home/tyler/ros_ws/src/amazon/msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::amazon::Object_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::amazon::Object_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amazon::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::amazon::Object_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amazon::Object_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::amazon::Object_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::amazon::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "6671b897f72603bddf255a606c9a6bba";
  }

  static const char* value(const ::amazon::Object_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x6671b897f72603bdULL;
  static const uint64_t static_value2 = 0xdf255a606c9a6bbaULL;
};

template<class ContainerAllocator>
struct DataType< ::amazon::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "amazon/Object";
  }

  static const char* value(const ::amazon::Object_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::amazon::Object_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
int64 bin_id\n\
int64 object_id\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::amazon::Object_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::amazon::Object_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.bin_id);
      stream.next(m.object_id);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct Object_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::amazon::Object_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::amazon::Object_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "bin_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.bin_id);
    s << indent << "object_id: ";
    Printer<int64_t>::stream(s, indent + "  ", v.object_id);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AMAZON_MESSAGE_OBJECT_H
