"""autogenerated by genpy from amazon/Grasp.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class Grasp(genpy.Message):
  _md5sum = "f1f713ed6e6433c0c4c83a5a25edd36b"
  _type = "amazon/Grasp"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int64 object_id
geometry_msgs/Point grasp_point

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z

"""
  __slots__ = ['object_id','grasp_point']
  _slot_types = ['int64','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       object_id,grasp_point

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(Grasp, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.object_id is None:
        self.object_id = 0
      if self.grasp_point is None:
        self.grasp_point = geometry_msgs.msg.Point()
    else:
      self.object_id = 0
      self.grasp_point = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_struct_q3d.pack(_x.object_id, _x.grasp_point.x, _x.grasp_point.y, _x.grasp_point.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      if self.grasp_point is None:
        self.grasp_point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.object_id, _x.grasp_point.x, _x.grasp_point.y, _x.grasp_point.z,) = _struct_q3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_struct_q3d.pack(_x.object_id, _x.grasp_point.x, _x.grasp_point.y, _x.grasp_point.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(_x))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(_x))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      if self.grasp_point is None:
        self.grasp_point = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 32
      (_x.object_id, _x.grasp_point.x, _x.grasp_point.y, _x.grasp_point.z,) = _struct_q3d.unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
_struct_q3d = struct.Struct("<q3d")
